version: '3'

services:
  mysql-development:
    image: 'mysql:${MYSQL_VERSION}'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      # - ./.mysql:/var/lib/mysql
      - ./init.sql:/tmp/init.sql
    command: --init-file /tmp/init.sql
  node-development:
    image: 'node:${NODE_VERSION}'
    depends_on:
      - mysql-development
    ports:
      - "${SERVER_PORT}:${NODE_PORT}"
    volumes:
      - .:/lockey
    working_dir: /lockey
    command: sh -c "npm install && sass sass:public/stylesheets && npm start"
    environment:
      - 'MYSQL_HOST=${MYSQL_HOST}'
      - 'MYSQL_PORT=${MYSQL_PORT}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'NODE_ENV=${NODE_ENV}'
      - 'PORT=${NODE_PORT}'
      - 'DEBUG=${DEBUG}'