version: '3'

services:
  mysql-development:
    image: mysql:8.0.31
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: lockey_db
      MYSQL_USER: lockey_usr
      MYSQL_PASSWORD: In2TheUnknown.
    ports:
      - "3308:3306"
    # volumes:
    #   - ./.mysql_data:/var/lib/mysql
  node-development:
    image: node:18.12.1-alpine3.15
    depends_on:
      - mysql-development
    ports:
      - "3000:3000"
    volumes:
      - .:/lockey
    working_dir: /lockey
    command: sh -c "npm install && npm run dev"